FROM python:3.12.2-slim
RUN apt update -y && install awscli -y  ##update apt and install aws since deploying on aws

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

CMD [ "python3","app.py" ]

