AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # depend upon model (here EficientNetV2)
BATCH_SIZE: 8 #depend upom machine
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2     #No features (output which need to detect)
WEIGHTS: imagenet  #already trained model on imagenet
LEARNING_RATE: 0.01


